name: Random daily commits ❇️

on:
  # Runs every day at 23:07 Asia/Manila  (15:07 UTC)
  schedule:
    - cron: '7 15 * * *'

jobs:
  spam:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Pull the repo contents
      - uses: actions/checkout@v4

      # 2️⃣  Decide how many commits (6‑15)
      - name: Pick random count
        id: rng
        run: echo "count=$(( RANDOM % 10 + 6 ))" >> "$GITHUB_OUTPUT"

      # 3️⃣  Make that many empty commits
      - name: Loop commits
        env:
          LOOPS: ${{ steps.rng.outputs.count }}
        run: |
          for n in $(seq 1 "$LOOPS"); do
            # random second inside the same UTC day
            secs=$(( RANDOM % 86400 ))
            ts=$(date -u -d "@$(( $(date -u +%s -d '00:00') + secs ))" '+%Y-%m-%dT%H:%M:%SZ')

            GIT_AUTHOR_DATE="$ts" \
            GIT_COMMITTER_DATE="$ts" \
            git commit --allow-empty -m "chore: auto‑commit #$n"
          done

      # 4️⃣  Push all commits back
      - name: Push back
        uses: ad-m/github-push-action@v0.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # --force-with-lease handles fast‑forwards if someone else pushed
          force: true
